Building configuration...

Current configuration:
!
frr version 8.4.4
frr defaults traditional
hostname 5eb561fc1c5e
domainname localdomain
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router rip
 network 192.168.5.0/29
 network 192.168.9.0/29
 network 192.100.1.0/29
 redistribute connected
 version 2
exit
!
end
