Building configuration...

Current configuration:
!
frr version 8.4.4
frr defaults traditional
hostname 17acb8801a77
domainname localdomain
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router ospf
 ospf router-id 4.4.4.4
 network 192.168.7.0/29 area 0
 network 192.168.8.0/29 area 0
exit
!
end
