Building configuration...

Current configuration:
!
frr version 8.4.4
frr defaults traditional
hostname 96d132b8981a
domainname localdomain
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router ospf
 ospf router-id 3.3.3.3
 network 192.100.1.0/29 area 0
 network 192.168.6.0/29 area 0
 network 192.168.7.0/29 area 0
exit
!
end
