Building configuration...

Current configuration:
!
frr version 8.4.4
frr defaults traditional
hostname 9957cc9456af
domainname localdomain
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router ospf
 ospf router-id 5.5.5.5
 network 192.100.2.0/29 area 0
 network 192.168.8.0/29 area 0
 network 192.168.9.0/29 area 0
exit
!
end
