Building configuration...

Current configuration:
!
frr version 8.4.4
frr defaults traditional
hostname cb7c1ef460e1
domainname localdomain
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router ospf
 ospf router-id 2.2.2.2
 network 192.100.2.0/29 area 0
 network 192.168.5.0/29 area 0
 network 192.168.6.0/29 area 0
exit
!
end
